Log:
  Level: debug

ExternalDomain: localhost:8080
ExternalPort: 8080
ExternalSecure: false

DefaultInstance:
  Org:
    Name: Papermerge
    Human:
      UserName: admin
      Password: Admin123!
      PasswordChangeRequired: true

  LoginPolicy:
    AllowUsernamePassword: true
    AllowRegister: true
    AllowExternalIDP: false
    ForceMFA: false
    PasswordlessEnabled: false

  PasswordComplexityPolicy:
    MinLength: 8
    HasLowercase: true
    HasUppercase: true
    HasNumber: true
    HasSymbol: true

  SMTPConfiguration:
    From: noreply@papermerge.local
    FromName: Papermerge DMS
    SMTP:
      Host: mailpit:1025
      User: ""
      Password: ""
      TLS: false
